import { fixContrast, type ThemeDefinition } from "./model.ts";

// Omarchy palettes: see THIRD_PARTY_THEMES.md. UI contrast is adapted for Gelabber.
const palettes: ThemeDefinition[] = [
  {
    version: 1,
    id: "dark",
    name: "Gelabber Dunkel",
    mode: "dark",
    style: "clear",
    colors: {
      background: "#17191a",
      panel: "#1d2021",
      surface: "#272b2d",
      rail: "#131617",
      text: "#eef0ee",
      muted: "#a4abb1",
      accent: "#f3b752",
      border: "#2c3032",
    },
  },
  {
    version: 1,
    id: "light",
    name: "Gelabber Hell",
    mode: "light",
    style: "clear",
    colors: {
      background: "#f8f5f0",
      panel: "#f4f0e9",
      surface: "#ece7df",
      rail: "#eee9e1",
      text: "#252829",
      muted: "#646d74",
      accent: "#e8a638",
      border: "#dcd6cc",
    },
  },
  {
    version: 1,
    id: "catppuccin",
    name: "Catppuccin",
    mode: "dark",
    style: "soft",
    colors: {
      background: "#1e1e2e",
      panel: "#161622",
      surface: "#313244",
      rail: "#101019",
      text: "#cdd6f4",
      muted: "#bac2de",
      accent: "#89b4fa",
      border: "#45475a",
    },
  },
  {
    version: 1,
    id: "catppuccin-latte",
    name: "Catppuccin Latte",
    mode: "light",
    style: "soft",
    colors: {
      background: "#eff1f5",
      panel: "#e3e4e8",
      surface: "#dce0e8",
      rail: "#d7d8dc",
      text: "#4c4f69",
      muted: "#5c5f77",
      accent: "#1e66f5",
      border: "#ccd0da",
    },
  },
  {
    version: 1,
    id: "nord",
    name: "Nord",
    mode: "dark",
    style: "clear",
    colors: {
      background: "#2e3440",
      panel: "#222730",
      surface: "#3b4252",
      rail: "#191c23",
      text: "#d8dee9",
      muted: "#adb5c4",
      accent: "#81a1c1",
      border: "#434c5e",
    },
  },
  {
    version: 1,
    id: "gruvbox",
    name: "Gruvbox",
    mode: "dark",
    style: "terminal",
    colors: {
      background: "#282828",
      panel: "#1e1e1e",
      surface: "#3c3836",
      rail: "#161616",
      text: "#d4be98",
      muted: "#bdae93",
      accent: "#7daea3",
      border: "#504945",
    },
  },
  {
    version: 1,
    id: "tokyo-night",
    name: "Tokyo Night",
    mode: "dark",
    style: "clear",
    colors: {
      background: "#1a1b26",
      panel: "#13141c",
      surface: "#24283b",
      rail: "#0e0e14",
      text: "#a9b1d6",
      muted: "#b4bee6",
      accent: "#7aa2f7",
      border: "#292e42",
    },
  },
  {
    version: 1,
    id: "everforest",
    name: "Everforest",
    mode: "dark",
    style: "soft",
    colors: {
      background: "#2d353b",
      panel: "#21272c",
      surface: "#343f44",
      rail: "#181d20",
      text: "#d3c6aa",
      muted: "#9da9a0",
      accent: "#7fbbb3",
      border: "#3d484d",
    },
  },
  {
    version: 1,
    id: "kanagawa",
    name: "Kanagawa",
    mode: "dark",
    style: "terminal",
    colors: {
      background: "#1f1f28",
      panel: "#17171e",
      surface: "#223249",
      rail: "#111116",
      text: "#dcd7ba",
      muted: "#c8c093",
      accent: "#dcd7ba",
      border: "#363646",
    },
  },
  {
    version: 1,
    id: "rose-pine",
    name: "Rosé Pine Dawn",
    mode: "light",
    style: "soft",
    colors: {
      background: "#faf4ed",
      panel: "#ede7e1",
      surface: "#f2e9e1",
      rail: "#e1dbd5",
      text: "#575279",
      muted: "#6e6a86",
      accent: "#56949f",
      border: "#dfdad9",
    },
  },
  {
    version: 1,
    id: "flexoki-light",
    name: "Flexoki Light",
    mode: "light",
    style: "clear",
    colors: {
      background: "#FFFCF0",
      panel: "#f2efe4",
      surface: "#E6E4D9",
      rail: "#e5e2d8",
      text: "#100F0F",
      muted: "#403E3C",
      accent: "#205EA6",
      border: "#CECDC3",
    },
  },
  {
    version: 1,
    id: "osaka-jade",
    name: "Osaka Jade",
    mode: "dark",
    style: "terminal",
    colors: {
      background: "#111c18",
      panel: "#0c1512",
      surface: "#23372B",
      rail: "#090f0d",
      text: "#C1C497",
      muted: "#D6D5BC",
      accent: "#509475",
      border: "#32473B",
    },
  },
  {
    version: 1,
    id: "matte-black",
    name: "Matte Black",
    mode: "dark",
    style: "clear",
    colors: {
      background: "#121212",
      panel: "#0d0d0d",
      surface: "#1e1e1e",
      rail: "#090909",
      text: "#bebebe",
      muted: "#8a8a8d",
      accent: "#e68e0d",
      border: "#2a2a2a",
    },
  },
  {
    version: 1,
    id: "ristretto",
    name: "Ristretto",
    mode: "dark",
    style: "soft",
    colors: {
      background: "#2c2525",
      panel: "#211b1b",
      surface: "#3d2f2a",
      rail: "#181414",
      text: "#e6d9db",
      muted: "#c3b7b8",
      accent: "#f38d70",
      border: "#403e41",
    },
  },
];
export const BUILTIN_THEMES = palettes.map(fixContrast);
export const BUILTIN_IDS = ["system", ...BUILTIN_THEMES.map((t) => t.id)];
export function builtinTheme(id: string): ThemeDefinition {
  return BUILTIN_THEMES.find((t) => t.id === id) ?? BUILTIN_THEMES[0];
}
